version: '2'

volumes:
 php-data:

services:
    api:
        image: docker-build-slimphp
        container_name: docker-build-slimphp
        build:
            context: ./
            dockerfile: ./docker/php56/Dockerfile
        command: php -S 0.0.0.0:8082 -t public
        environment:
            docker: "true"
        ports:
            - 8082:8082
        volumes:
            - .:/var/www/html
            - php-data:/var/www/html/vendor/



